export const ORANGE_OUTLINE_COLOR = "#ffa500";
export const BLACK_OUTLINE_COLOR = "#000000";
export const GREEN_OUTLINE_COLOR = "#0FFF50";
export const STICKY_NOTE_BACKGROUND_COLOR = "#EDD88C";
export const PROHIBIT_SELECTION = "noHop";
export const ALPHABET = [
  "a",
  "b",
  "c",
  "d",
  "e",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  "m",
  "n",
  "o",
  "p",
  "q",
  "r",
  "s",
  "t",
  "u",
  "v",
  "w",
  "x",
  "y",
  "z",
];
export const SEMANTIC_NODES = {
  BODY: "<body>",
  H1: "<h1>",
  H2: "<h2>",
  H3: "<h3>",
  H4: "<h4>",
  H5: "<h5>",
  H6: "<h6>",
  P: "<p>",
  A: "<a>",
  UL: "<ul>",
  OL: "<ol>",
  LI: "<li>",
  DL: "<dl>",
  DT: "<dt>",
  DD: "<dd>",
  LINK: "<link>",
  BR: "<br>",
  HR: "<hr>",
  ARTICLE: "<article>",
  ASIDE: "<aside>",
  DETAILS: "<details>",
  FIGCAPTION: "<figcaption>",
  FIGURE: "<figure>",
  MARK: "<mark>",
  SUMMARY: "<summary>",
  TIME: "<time>",
  FOOTER: "<footer>",
  HEADER: "<header>",
  MAIN: "<main>",
  NAV: "<nav>",
  SECTION: "<section>",
  ABBR: "<abbr>",
  ADDRESS: "<address>",
  BLOCKQUOTE: "<blockquote>",
  CITE: "<cite>",
  CODE: "<code>",
  DFN: "<dfn>",
  Q: "<q>",
  SAMP: "<samp>",
  VAR: "<var>",
  FORM: "<form>",
  INPUT: "<input>",
  TEXTAREA: "<textarea>",
  BUTTON: "<button>",
  SELECT: "<select>",
  OPTION: "<option>",
  LABEL: "<label>",
  FIELDSET: "<fieldset>",
  LEGEND: "<legend>",
  OUTPUT: "<output>",
  IFRAME: "<iframe>",
  IMG: "<img>",
  MAP: "<map>",
  AREA: "<area>",
  CANVAS: "<canvas>",
  PICTURE: "<picture>",
  SVG: "<svg>",
  VIDEO: "<video>",
  TRACK: "<track>",
  TABLE: "<table>",
  CAPTION: "<caption>",
  TH: "<th>",
  TR: "<tr>",
  TD: "<td>",
  THEAD: "<thead>",
  TBODY: "<tbody>",
  TFOOT: "<tfoot>",
  SPAN: "<span>",
  DIALOG: "<dialog>",
};
