export const ORANGE_OUTLINE_COLOR = "#ffa500";
export const BLACK_OUTLINE_COLOR = "#000000";
export const GREEN_OUTLINE_COLOR = "#0FFF50";
export const STICKY_NOTE_BACKGROUND_COLOR = "#EDD88C";
export const PROHIBIT_SELECTION = "noHop";
export const FORCE_ALLOW_SELECTION = "yesHop";
export const ALPHABET = [
  "a",
  "b",
  "c",
  "d",
  "e",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  "m",
  "n",
  "o",
  "p",
  "q",
  "r",
  "s",
  "t",
  "u",
  "v",
  "w",
  "x",
  "y",
  "z",
];
export const SEMANTIC_NODES = {
  BODY: "<body>",
  H1: "<h1>",
  H2: "<h2>",
  H3: "<h3>",
  H4: "<h4>",
  H5: "<h5>",
  H6: "<h6>",
  P: "<p>",
  A: "<a>",
  UL: "<ul>",
  OL: "<ol>",
  LI: "<li>",
  DL: "<dl>",
  DT: "<dt>",
  DD: "<dd>",
  LINK: "<link>",
  BR: "<br>",
  HR: "<hr>",
  ARTICLE: "<article>",
  ASIDE: "<aside>",
  DETAILS: "<details>",
  FIGCAPTION: "<figcaption>",
  FIGURE: "<figure>",
  MARK: "<mark>",
  SUMMARY: "<summary>",
  TIME: "<time>",
  FOOTER: "<footer>",
  HEADER: "<header>",
  MAIN: "<main>",
  NAV: "<nav>",
  SECTION: "<section>",
  ABBR: "<abbr>",
  ADDRESS: "<address>",
  BLOCKQUOTE: "<blockquote>",
  CITE: "<cite>",
  CODE: "<code>",
  DFN: "<dfn>",
  Q: "<q>",
  SAMP: "<samp>",
  VAR: "<var>",
  FORM: "<form>",
  INPUT: "<input>",
  TEXTAREA: "<textarea>",
  BUTTON: "<button>",
  SELECT: "<select>",
  OPTION: "<option>",
  LABEL: "<label>",
  FIELDSET: "<fieldset>",
  LEGEND: "<legend>",
  OUTPUT: "<output>",
  IFRAME: "<iframe>",
  IMG: "<img>",
  MAP: "<map>",
  AREA: "<area>",
  CANVAS: "<canvas>",
  PICTURE: "<picture>",
  SVG: "<svg>",
  VIDEO: "<video>",
  SOURCE: "<source>",
  TRACK: "<track>",
  TABLE: "<table>",
  CAPTION: "<caption>",
  TH: "<th>",
  TR: "<tr>",
  TD: "<td>",
  THEAD: "<thead>",
  TBODY: "<tbody>",
  TFOOT: "<tfoot>",
  SPAN: "<span>",
  DIALOG: "<dialog>",
};
export const INTERACTION_NODES = {
  A: "<a>",
  DETAILS: "<details>",
  NAV: "<nav>",
  ABBR: "<abbr>",
  FORM: "<form>",
  INPUT: "<input>",
  TEXTAREA: "<textarea>",
  BUTTON: "<button>",
  SELECT: "<select>",
  OPTION: "<option>",
  FIELDSET: "<fieldset>",
  OUTPUT: "<output>",
  MAP: "<map>",
  AREA: "<area>",
  VIDEO: "<video>",
  SOURCE: "<source>",
  DIALOG: "<dialog>",
};
//Selected from the list of all events: https://www.w3schools.com/jsref/dom_obj_event.asp
export const USER_INTERACTION_EVENTS = {
  ABORT: "abort",
  BLUR: "blur",
  CHANGE: "change",
  CLICK: "click",
  CONTEXTMENU: "contextmenu",
  COPY: "copy",
  CUT: "cut",
  DBLCLICK: "dblclick",
  DRAG: "drag",
  DRAGEND: "dragend",
  DRAGENTER: "dragenter",
  DRAGLEAVE: "dragleave",
  DRAGOVER: "dragover",
  DRAGSTART: "dragstart",
  DROP: "drop",
  FOCUS: "focus",
  FOCUSIN: "focusin",
  FOCUSOUT: "focusout",
  FULLSCREENCHANGE: "fullscreenchange",
  FULLSCREENERROR: "fullscreenerror",
  INPUT: "input",
  INVALID: "invalid",
  KEYDOWN: "keydown",
  KEYPRESS: "keypress",
  KEYUP: "keyup",
  MOUSEDOWN: "mousedown",
  MOUSEENTER: "mouseenter",
  MOUSELEAVE: "mouseleave",
  MOUSEMOVE: "mousemove",
  MOUSEOVER: "mouseover",
  MOUSEOUT: "mouseout",
  MOUSEUP: "mouseup",
  PAGEHIDE: "pagehide",
  PAGESHOW: "pageshow",
  PASTE: "paste",
  PLAY: "play",
  PLAYING: "playing",
  RESIZE: "resize",
  RESET: "reset",
  SCROLL: "scroll",
  SEARCH: "search",
  SEEKED: "seeked",
  SEEKING: "seeking",
  SELECT: "select",
  SHOW: "show",
  SUBMIT: "submit",
  TIMEUPDATE: "timeupdate",
  TOGGLE: "toggle",
  WHEEL: "wheel",
};
